name: autobuild

on:
  push:
  pull_request:
  release:
    types: published

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v4

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .

    - name: Make package
      run: tar -zcvf NoteIsSite.tar.gz NoteIsSite

    - name: Upload Release on push tag
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: NoteIsSite.tar.gz
        asset_name: NoteIsSite_${{ github.ref }}.tar.gz
